### ISSUE TITLE
Der Spinner "Fix time" darf nicht auf der ersten Seite sein, sondern es soll der Spinner auf dem Monitoring-Tab verwendet werden

### ISSUE THREAD

**Issue by htl-leonding** [alexpichler99/Testumgebung#45]
<img width="936" alt="screen shot 2018-04-16 at 08 43 59" src="https://user-images.githubusercontent.com/14834294/38793668-780fdbb0-4152-11e8-9cd2-bceb310940e1.png">

**Comment by alexpichler99** [comment]
Fixed cf98abdc67756b05886553e02933453a908d0731
